apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: question-service-redis
  namespace: peerprep
  labels:
    app: question-service-redis
spec:
  serviceName: question-service-redis-service
  replicas: 1
  selector:
    matchLabels:
      app: question-service-redis
  template:
    metadata:
      labels:
        app: question-service-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6380
              name: redis
          command:
            - redis-server
            - --appendonly
            - 'yes'
            - --save
            - '60 1'
            - --port
            - '6380'
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          livenessProbe:
            tcpSocket:
              port: 6380
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6380
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: question-service-redis-service
  namespace: peerprep
  labels:
    app: question-service-redis
spec:
  clusterIP: None # Headless service for StatefulSet
  selector:
    app: question-service-redis
  ports:
    - port: 6380
      targetPort: 6380
      protocol: TCP
      name: redis
