apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  namespace: peerprep
  labels:
    app: matching-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      serviceAccountName: matching-service-sa # Workload Identity for Secret Manager
      containers:
        - name: matching-service
          image: gcr.io/peerprep-475911/matching-service:v2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
              name: http
          envFrom:
            - configMapRef:
                name: matching-service-config
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
