apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: peerprep
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: api-gateway
  namespace: peerprep
subsets:
  - addresses:
      - ip: 34.118.237.65
    ports:
      - name: http
        port: 8000
        protocol: TCP
