apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: peerprep
  labels:
    app: api-gateway
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: api-gateway
  namespace: peerprep
subsets:
  - addresses:
      - ip: 34.124.186.128  # Kong LoadBalancer external IP
    ports:
      - name: http
        port: 80
        protocol: TCP
