apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: collaboration-websocket-config
  namespace: peerprep
spec:
  connectionDraining:
    drainingTimeoutSec: 60

  timeoutSec: 86400  # 24 hours for long-lived WebSocket connections
  
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 8002

  sessionAffinity:
    affinityType: 'CLIENT_IP'
    affinityCookieTtlSec: 10800
