apiVersion: v1
kind: Service
metadata:
  name: collaboration-service
  namespace: peerprep
  labels:
    app: collaboration-service
spec:
  type: ClusterIP
  selector:
    app: collaboration-service
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
