apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: peerprep
  labels:
    app: matching-service
  annotations:
    cloud.google.com/backend-config: '{"default": "matching-websocket-config"}'
spec:
  type: ClusterIP
  selector:
    app: matching-service
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
    name: websocket
