apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: peerprep
  labels:
    app: matching-service
spec:
  type: LoadBalancer
  selector:
    app: matching-service
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
    name: websocket
