apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: peerprep
  labels:
    app: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
