version: '3.8'

services:
  # Redis service
  redis:
    image: redis:7-alpine
    container_name: peerprep-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - peerprep-network

  # User Service
  user-service:
    build: .
    container_name: peerprep-user-service
    ports:
      - "3001:3001"
    env_file:
      - .env.docker
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - peerprep-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  peerprep-network:
    driver: bridge